### ISSUE TITLE
harvester login failing: with invalid character 'p' after top-level value

### ISSUE THREAD

**Issue by mjbright** [belgaied2/harvester-cli#20]
New to Harvester, new to harvester-cli I'm attempting to login to my server.

Testing with versions:
```
Harvester Version:     v1.1.1 
harvester-cli version v0.1.2
```

I've tried the below ```harvester login``` commands from both macOS and Linux but get  the same ```invalid character 'p' after top-level value``` error message
- macOS Ventura 13.0.1
- Ubuntu Linux 20.04.4 LTS

(Documenting for myself so I can find it again !!:)
I created a token at the dashboard account settings (top-left)

I created a ca.crt file, by extracting and base64 decoding the rke2.yaml kubeconfig file.

On macOS:
```
harvester login https://192.168.0.91 -t "token-mcx4w:h7nvv2zjrrBAD-TOKENxwpc9z886pbntlq4s9tpb2mg8nz8wgzzf6b" --cacert ca.crt
FATA[0000] unable to parse response from https://192.168.0.91/v3/settings/cacerts
Error: invalid character 'p' after top-level value
Response:
404 page not found
```

On Linux:
```
 harvester login https://192.168.0.91 -t "token-mcx4w:h7nvv2zjrrBAD-TOKENxwpc9z886pbntlq4s9tpb2mg8nz8wgzzf6b" --cacert /tmp/ca.crt
FATA[0000] unable to parse response from https://192.168.0.91/v3/settings/cacerts
Error: invalid character 'p' after top-level value
Response:
404 page not found
```

I didn't find a simple howto for the setup, so had to claw my way through various doc pages, the API and dashboard to get this far.  I'd be happy to contribute such a page when this is solved.

**Comment by mjbright** [comment]
Curiously, I just tried the terraform provider which worked straight off with a simple KUBECONFIG setting (to rke2.yaml).

Makes me wonder if it would make sense to be able to specify the path to an initial KUBECONFIG (rke2.yaml) for ```harvester login```

**Comment by belgaied2** [comment]
Oh, nice to see some movement here.
Yes, you can use the kubeconfig, by putting it in `$HOME/.harvester/config` and you would not need the `harvester login` command anymore.

**Comment by belgaied2** [comment]
As for the login command, I will need to check that out with Harvester v1.1.1, which was not tested until now.

**Comment by belgaied2** [comment]
I checked the `harvester login` command with Harvester v1.1.1 and everything works fine.
I would suggest trying to remove the `--cacert` flag and retry.

Also, if you are okay with that, I will soon close this issue.
