### ISSUE TITLE
add https://github.com/harvester/vm-import-controller -Support

### ISSUE THREAD

**Issue by ne0YT** [belgaied2/harvester-cli#21]
would be nice to be able to have a simple one-stop solution :)

**Comment by belgaied2** [comment]
Hi @ne0YT , thanks a lot for the issue. 
Well, it does look interesting to integrate with the VM Import Controller. Did you have a use case in mind? How would you want it to work to help you in your workflow ?

**Comment by ne0YT** [comment]
> Hi @ne0YT , thanks a lot for the issue. Well, it does look interesting to integrate with the VM Import Controller. Did you have a use case in mind? How would you want it to work to help you in your workflow ?
hey there
my problem is a bit that I don't understand how to use the VM Import (where to create which file to start migrating vms) so it would be very cool to have a similarly simple cli like this tool provides to migrate vm's especially from vCenter. currently I do it manually on my client device.. :)

**Comment by ne0YT** [comment]
> Thanks @ne0YT for the feedback. Cool, I understand your need now. Would you prefer to set up your VM Import settings for vcenter using a CLI prompt ? I will try to provide that feature in `harvester-cli` but please be patient, I am doing this on the side, with a relatively limited amount of time available.

yes, would be great to have this :)
but I think the other feature is much more needed, as of now it's only supported to have a net which is called vlan1 right?
https://github.com/belgaied2/harvester-cli/issues/22

**Comment by ne0YT** [comment]
can you publish instructions to do so?
How to do a migration from vcenter to harvester.
