### ISSUE TITLE
Combine Template with modifications (--cloud-init-user-data, --disk-size)

### ISSUE THREAD

**Issue by ne0YT** [belgaied2/harvester-cli#22]
especially because of this:
```!!IMPORTANT NOTE: At the moment, the create sub-command supposes a Network vlan1 already exists!!```
But also because there might be some vms only running with special configs.

it would be cool to be able to pass all of these while using a template:
--disk-size
--cpus
--memory
--cloud-init-user-data
--cloud-init-network-data

do you have an example of the usage for how to pass this data?:
--cloud-init-user-data
#cloud-config
runcmd:
  - $var1 = testvalue1
  - wget https://mytestpagewichdeliversa.sh
  - chmod +x ./a.sh
  - ./a.sh
--cloud-init-network-data
network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      dhcp4: no
      addresses: [10.10.10.100/24]
      gateway4: 10.10.10.250
      nameservers:
        addresses: [1.1.1.1, 8.8.8.8]

**Comment by ne0YT** [comment]
@belgaied2 hey there, is this smh possible or should I start a fresh project?

**Comment by ne0YT** [comment]
@belgaied2 hey there
do you think you can do something in this relation the next few days?

**Comment by belgaied2** [comment]
Hi @ne0YT ,

I am starting to work on this. I will update you soon.

**Comment by belgaied2** [comment]
Hi @ne0YT ,

This should be implemented in the commit 1dfb09c. However, no release yet. Feel free to check out the code and compile it to test it.

**Comment by ne0YT** [comment]
@belgaied2 Im not able to build it:
go build -o harvester-cli.exe
# github.com/c9s/goprocinfo/linux
..\..\go\pkg\mod\github.com\c9s\goprocinfo@v0.0.0-20210130143923-c95fcf8c64a8\linux\disk.go:15:16: undefined: syscall.Statfs_t
..\..\go\pkg\mod\github.com\c9s\goprocinfo@v0.0.0-20210130143923-c95fcf8c64a8\linux\disk.go:16:17: undefined: syscall.Statfs

**Comment by ne0YT** [comment]
https://github.com/belgaied2/harvester-cli/issues/36
