### ISSUE TITLE
I tried to pass --cloud-init-user-data & --cloud-init-network-data as files and as a oneliner-version of the yaml scripts

### ISSUE THREAD

**Issue by ne0YT** [belgaied2/harvester-cli#24]
but it will always fail with:
"config map was not found, please specify another configmap"
so I cannot use a custom config which is not already on harvester?

**Comment by belgaied2** [comment]
Hi @ne0YT , Thanks for all these new issues, I am working on some of these currently, like choosing a specific network.

For this issue, it needs indeed an existing ConfigMap, but I have been thinking about making a file also possible. Do you consider this as an important feature for you?

**Comment by ne0YT** [comment]
> Hi @ne0YT , Thanks for all these new issues, I am working on some of these currently, like choosing a specific network.
> 
> For this issue, it needs indeed an existing ConfigMap, but I have been thinking about making a file also possible. Do you consider this as an important feature for you?

It is very important for me :)
Depending on when it's working or not I'm gonna figure it out using selenium till then.

**Comment by ne0YT** [comment]
https://github.com/belgaied2/harvester-cli/issues/36
