### ISSUE TITLE
support create from template

### ISSUE THREAD

**Issue by abonillabeeche** [belgaied2/harvester-cli#3]
It would be the simplest way to create a new vm to just reference a template. 

harvester vm create --template ubuntu20-4-Large

**Comment by belgaied2** [comment]
Hi @abonillabeeche , thanks for the suggestion, it is a very good, I am analyzing it right now.

**Comment by belgaied2** [comment]
This should be solved in the commit 702cd395dd6381ef7b06980de6e42576ac8ce572.
