### ISSUE TITLE
[FEATURE] Support Multiple Instances creation

### ISSUE THREAD

**Issue by abonillabeeche** [belgaied2/harvester-cli#4]
The UI allows us to select "Multiple Instances" "Count" to create several VMs, that is from a fully defined VM in the CLI or from a template. Can we introduce this? Perhaps
--multiple 3
or
--count 3
so it maintains the wording from the UI

**Comment by belgaied2** [comment]
This is implemented in the commit 9c0eb2859639b8d5638bd70ee647b4fe9752cf1e and will be available in version v0.0.4.
