### ISSUE TITLE
[FEATURE] support listing templates

### ISSUE THREAD

**Issue by abonillabeeche** [belgaied2/harvester-cli#5]
Since we allow the creation of VMs via --template, it would be ideal to support listing the available templates.

```
harvester template list
```
?

**Comment by belgaied2** [comment]
What kind of data do you suggest to show for the `template list` command ?
Only Name and LatestVersion or more ?

**Comment by abonillabeeche** [comment]
I'm ok with the name. If we can use the version with the CLI then that would be ideal too.

**Comment by belgaied2** [comment]
I have the following already done, but it does not look useful.
![image](https://user-images.githubusercontent.com/60746935/150505499-f4767481-380a-425d-85d0-c22f7c826cb3.png)
What would be interesting to show ?

**Comment by belgaied2** [comment]
This is implemented in the commit bbf0152b541b21a91e8c7112250d2f5180e17dc1 and available in the release [v0.0.5](https://github.com/belgaied2/harvester-cli/releases/tag/v0.0.5)
